from __future__ import annotations

from enum import StrEnum


class RuntimeErrorCode(StrEnum):
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    RUNTIME_OVERLOADED = "RUNTIME_OVERLOADED"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_PARSE_FAILED = "MODEL_PARSE_FAILED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_PERMISSION_DENIED = "TOOL_PERMISSION_DENIED"
    BUSINESS_DATA_INVALID = "BUSINESS_DATA_INVALID"
    SAFETY_BLOCKED = "SAFETY_BLOCKED"
    COST_LIMIT_EXCEEDED = "COST_LIMIT_EXCEEDED"
    CALLBACK_SIGNATURE_INVALID = "CALLBACK_SIGNATURE_INVALID"
    CALLBACK_OUT_OF_ORDER = "CALLBACK_OUT_OF_ORDER"
    RECONCILIATION_NEEDED = "RECONCILIATION_NEEDED"
    INDIRECT_PROMPT_INJECTION = "INDIRECT_PROMPT_INJECTION"
    GENERATION_SUPERSEDED = "GENERATION_SUPERSEDED"
    DISPATCH_FAILED = "DISPATCH_FAILED"
    PACKAGE_REVOKED = "PACKAGE_REVOKED"
    PRIVATE_DATA_PURGED = "PRIVATE_DATA_PURGED"
    AUTHORIZATION_REVOKED = "AUTHORIZATION_REVOKED"
    ACTIVE_TIME_LIMIT_EXCEEDED = "ACTIVE_TIME_LIMIT_EXCEEDED"
    RUN_DEADLINE_EXCEEDED = "RUN_DEADLINE_EXCEEDED"
    SEMANTIC_VALIDATION_FAILED = "SEMANTIC_VALIDATION_FAILED"
